
site_name: Sergio Gao's Page
site_url: https://gsjz.github.io
site_author: SergioGao
site_description: 高书捷的主页

nav:
  - 应用与计算数学:
    - 应用与计算数学/index.md
    - 历年真题:
      - 应用与计算数学/历年真题/2024.md
    - 线性和非线性规划:
      - 应用与计算数学/线性和非线性规划/单纯形法.md
      - 应用与计算数学/线性和非线性规划/内点法.md
      - 应用与计算数学/线性和非线性规划/罚函数法.md
      - 应用与计算数学/线性和非线性规划/牛顿法.md
      - 应用与计算数学/线性和非线性规划/同伦法.md
      - 应用与计算数学/线性和非线性规划/不动点法.md
      - 应用与计算数学/线性和非线性规划/动态规划.md
      
  - 本科学习:
    - 本科学习/index.md
    - 公开课程:
      - CMU15-445:
        - 本科学习/公开课程/CMU15-445/index.md
        - 本科学习/公开课程/CMU15-445/lec1.md
        - 本科学习/公开课程/CMU15-445/lec2.md
        - 本科学习/公开课程/CMU15-445/hw1.md
        - 本科学习/公开课程/CMU15-445/proj0.md
        - 补课:
          - 本科学习/公开课程/CMU15-445/补课/git 相关.md
          - 本科学习/公开课程/CMU15-445/补课/杂项.md
      - SUCS229:
        - 本科学习/公开课程/SUCS229/index.md
        - 本科学习/公开课程/SUCS229/lec1.md
        - 本科学习/公开课程/SUCS229/lec2.md
        - 本科学习/公开课程/SUCS229/hw0.md
        - 本科学习/公开课程/SUCS229/hw1.md
    - 考研内容:
      - 408:
        - 本科学习/考研内容/408/杂记/250922.md
        - 本科学习/考研内容/408/杂记/250924.md
        - 本科学习/考研内容/408/杂记/250926.md
        - 本科学习/考研内容/408/杂记/250928.md
        - 本科学习/考研内容/408/杂记/251002.md
        - 本科学习/考研内容/408/杂记/251011.md
        - 本科学习/考研内容/408/杂记/251013.md
        - 本科学习/考研内容/408/杂记/251016.md
        - 本科学习/考研内容/408/CN/局域网.md
        - 本科学习/考研内容/408/DS/堆排序.md
        - 本科学习/考研内容/408/DS/线索二叉树.md
        - 本科学习/考研内容/408/OS/进程与线程.md
        - 本科学习/考研内容/408/CO/计算集系统层次结构.md
        
        
      - 数学:
        - 本科学习/考研内容/数学/高数期末.md
        - 本科学习/考研内容/数学/08数一.md
        - 本科学习/考研内容/数学/概率论.md
        - 本科学习/考研内容/数学/线性代数.md
        
        
      - 政治:
        - 本科学习/考研内容/政治/近代史期末.md
        - 本科学习/考研内容/政治/思想道德期末.md
    - 本科通识:
      - 大学物理:
        - 本科学习/本科通识/大学物理/量子物理基础.md
        - 本科学习/本科通识/大学物理/相对论.md
  - XCPC:
    - XCPC/index.md
    - 分类题解:
      - XCPC/分类题解/笛卡尔树.md
      - XCPC/分类题解/凸优化相关.md
      - XCPC/分类题解/网络流.md
      - XCPC/分类题解/特殊 MST.md
      - XCPC/分类题解/树上计数.md
      - XCPC/分类题解/Tarjan 相关.md
      - XCPC/分类题解/多项式相关.md
      - XCPC/分类题解/Min-max 容斥.md
      - XCPC/分类题解/中国剩余定理.md
      - XCPC/分类题解/异或线性基.md
      - XCPC/分类题解/杜教筛.md
      - XCPC/分类题解/Fibonacci 数.md
    - 普通题解:
      - XCPC/普通题解/杂题集一.md
      - XCPC/普通题解/杂题集二.md
      - XCPC/普通题解/杂题集三.md
    - 模板与课件:
      - XCPC/模板与课件/参赛模板.md
      - XCPC/模板与课件/Min-Max 容斥课件.md
      - 算法可视化:
        - AC 自动机: XCPC/模板与课件/算法可视化/AC-automaton.html
        - 后缀自动机: XCPC/模板与课件/算法可视化/suffix-automaton.html
        - Dinic 最大流: XCPC/模板与课件/算法可视化/Dinic-flow.html
        - Dijkstra 费用流: XCPC/模板与课件/算法可视化/Dijkstra-cost-flow.html
        - 草稿: XCPC/模板与课件/算法可视化/draft.html
      - 家教记录: 
        - yzl_lec1: XCPC/模板与课件/reveal.js/yzl_lec1.html
        - yzl_lec2: XCPC/模板与课件/reveal.js/yzl_lec2.html
        - yzl_lec3: XCPC/模板与课件/reveal.js/yzl_lec3.html
        - yzl_lec4: XCPC/模板与课件/reveal.js/yzl_lec4.html
        - yzl_lec5: XCPC/模板与课件/reveal.js/yzl_lec5.html
        - yzl_lec6: XCPC/模板与课件/reveal.js/yzl_lec6.html  


theme:
  name: material
  
  logo: images/GClef.svg
  favicon: images/GClef_black.svg
  
  font:
    code: Fira Code

  palette:
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - content.code.copy
    
    - navigation.tracking

  language: zh
copyright: SergioGao CC-BY-4.0
extra:
    
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/gsjz

plugins:
  - search:
      lang:
        - zh
        - en
        - ja
  - meta
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - mkdocs/javascripts/katex.js
  - mkdocs/javascripts/katex.min.js
  - mkdocs/javascripts/copy-tex.js
  - mkdocs/javascripts/auto-render.min.js
  - mkdocs/javascripts/mermaid-init.js
extra_css:
  - mkdocs/css/katex.min.css
  - mkdocs/css/no-footer.css
  - mkdocs/css/unordered-list-symbols.css
  - mkdocs/css/extra.css
