# [Info]
# 左上角标题
site_name: Sergio Gao's Page
site_url: https://gsjz.github.io
site_author: SergioGao
site_description: 高书捷的主页

# [Navigtion]
nav:
  - XCPC:
    - XCPC/index.md
    - 分类题解:
      - XCPC/分类题解/笛卡尔树.md
      - XCPC/分类题解/凸优化相关.md
      - XCPC/分类题解/网络流.md
      - XCPC/分类题解/特殊 MST.md
      - XCPC/分类题解/树上计数.md
      - XCPC/分类题解/Tarjan 相关.md
      - XCPC/分类题解/多项式相关.md
      - XCPC/分类题解/Min-max 容斥.md
      - XCPC/分类题解/中国剩余定理.md
      - XCPC/分类题解/异或线性基.md
      - XCPC/分类题解/杜教筛.md
      - XCPC/分类题解/Fibonacci 数.md
    - 普通题解:
      - XCPC/普通题解/杂题集一.md
      - XCPC/普通题解/杂题集二.md
      - XCPC/普通题解/杂题集三.md
    - 模板与课件:
      - XCPC/模板与课件/参赛模板.md
      - XCPC/模板与课件/Min-Max 容斥课件.md
      - 算法可视化:
        - AC 自动机: XCPC/模板与课件/算法可视化/AC-automaton.html
        - 后缀自动机: XCPC/模板与课件/算法可视化/suffix-automaton.html
        - Dinic 最大流: XCPC/模板与课件/算法可视化/Dinic-flow.html
        - Dijkstra 费用流: XCPC/模板与课件/算法可视化/Dijkstra-cost-flow.html
        - 草稿: XCPC/模板与课件/算法可视化/draft.html
      - 家教记录: 
        - yzl_lec1: XCPC/模板与课件/reveal.js/yzl_lec1.html
        - yzl_lec2: XCPC/模板与课件/reveal.js/yzl_lec2.html
        - yzl_lec3: XCPC/模板与课件/reveal.js/yzl_lec3.html
        - yzl_lec4: XCPC/模板与课件/reveal.js/yzl_lec4.html
        - yzl_lec5: XCPC/模板与课件/reveal.js/yzl_lec5.html
        - yzl_lec6: XCPC/模板与课件/reveal.js/yzl_lec6.html
  - 本科学习:
    - 本科学习/index.md
    - 公开课程:
      - CMU15-445:
        - 本科学习/公开课程/CMU15-445/index.md
        - 本科学习/公开课程/CMU15-445/lec1.md
        - 本科学习/公开课程/CMU15-445/lec2.md
        - 本科学习/公开课程/CMU15-445/hw1.md
        - 本科学习/公开课程/CMU15-445/proj0.md
        - 补课:
          - 本科学习/公开课程/CMU15-445/补课/git 相关.md
          - 本科学习/公开课程/CMU15-445/补课/杂项.md
      - SUCS229:
        - 本科学习/公开课程/SUCS229/index.md
        - 本科学习/公开课程/SUCS229/lec1.md
        - 本科学习/公开课程/SUCS229/lec2.md
        - 本科学习/公开课程/SUCS229/hw0.md
        - 本科学习/公开课程/SUCS229/hw1.md
    - 考研内容:
      - 408:
        - 本科学习/考研内容/408/杂记/250922.md
        - 本科学习/考研内容/408/杂记/250924.md
        - 本科学习/考研内容/408/杂记/250926.md
        - 本科学习/考研内容/408/杂记/250928.md
        - 本科学习/考研内容/408/杂记/251002.md
        - 本科学习/考研内容/408/杂记/251011.md
        - 本科学习/考研内容/408/杂记/251013.md
        - 本科学习/考研内容/408/CN/局域网.md
        - 本科学习/考研内容/408/DS/堆排序.md
        - 本科学习/考研内容/408/DS/线索二叉树.md
        - 本科学习/考研内容/408/OS/进程与线程.md
        
      - 数学:
        - 本科学习/考研内容/数学/高数期末.md
        - 本科学习/考研内容/数学/08数一.md
      - 政治:
        - 本科学习/考研内容/政治/近代史期末.md
        - 本科学习/考研内容/政治/思想道德期末.md
    - 本科通识:
      - 大学物理:
        - 本科学习/本科通识/大学物理/量子物理基础.md
        - 本科学习/本科通识/大学物理/相对论.md
      - 雅思英语:
        - 本科学习/本科通识/雅思英语/5-1.md

# [UI]
# [top]
theme:
  name: material
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  
  logo: images/GClef.svg
  favicon: images/GClef_black.svg
  
  font:
    code: Fira Code

  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: black
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    # - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    # - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    # - content.action.edit
    
    - navigation.tracking
    

  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    # repo: fontawesome/brands/github
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
# edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
# repo_url: https://github.com/gsjz/gsjz.github.io
# repo_name: gsjz.github.io
# [bottom-left corner]
# [版权说明]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: SergioGao CC-BY-4.0
# [bottom-right corner]
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
    
  social: # icons
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/gsjz

# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  - meta
markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css